### ISSUE TITLE
Missing breadcrumbs

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-unhcr#24]
We seem to have lost the breadcrumbs in the new theme

**Comment by amercader** [comment]
Here are the blocks on the core templates: 
https://github.com/ckan/ckan/blob/master/ckan/templates/page.html#L37

**Comment by smth** [comment]
This was intentional. I have now reenabled the breadcrumb on the resource page (https://github.com/okfn/ckanext-unhcr/commit/2a96e0811719f635bb2e9b1bbdd1fb87b1cafea2), as this information wasn't otherwise available there.

Note: "Data Containers" links to organizations (also noted in https://github.com/okfn/ckanext-unhcr/issues/4#issuecomment-372341213)
