### ISSUE TITLE
Duplicated activity entries when editing a dataset

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-unhcr#248]
![imgpsh_fullsize_anim](https://user-images.githubusercontent.com/200230/70699585-a75b3c80-1cc9-11ea-854c-7321533539bb.png)

This is probably caused by the background jobs fired up on every update to compute dataset fields, etc. We should probably use the config option to hide activities from certain users (although by default the site user ones are not shown IIRC so there might be something else at play here)

**Comment by chris48s** [comment]
I had a look at this one.. I think the reason the events aren't getting filtered out is because if I call

`toolkit.config.get('ckan.hide_activity_from_users')`

it returns `'default'`.

If that returned either `'ridl'` or `None`, it would work.

The easy fix here is to set `CKAN__HIDE_ACTIVITY_FROM_USERS=ridl` in the deploy repo and move on, but I'm slightly unclear on how we're ending up with this value set to `'default'` in the first place. I think it should take the value of `toolkit.config.get('ckan.site_id')` (which is `'ridl'`) if we haven't explictly set it to anything (which we haven't, as far as I can see).

Thoughts?

**Comment by amercader** [comment]
It's default because the value comes from the `production.ini` file generated on the image. This file uses the `ckan.site_id` *in the file* to set this variable [here](https://github.com/ckan/ckan/blob/master/ckan/config/deployment.ini_tmpl#L186). As the file has a site id of `default`, that's what `ckan.hide_activity_from_users` is being set to.
So yes, let's set the env var you suggest and that will override this setting.

Did you change the site id from `unhcr` to `ridl`? Looks like the site user used before was `unhcr`:

https://ridl.unhcr.org/user/activity/unhcr
vs
https://ridl.unhcr.org/user/activity/ridl

**Comment by chris48s** [comment]
> Did you change the site id from `unhcr` to `ridl`?

Wasn't me :see_no_evil:  Looks like it got changed when @roll set up the new env files in the AWS repo and I didn't notice:
https://github.com/okfn/docker-ckan-unhcr/blob/0e041ef27621d636a8ce7a3b0794dd3b96b3ebe7/.web.common.env#L3
https://github.com/okfn/docker-ckan-unhcr-aws/blob/2984006677a8703f15dfa3d36cc70c6e2b7afc30/ckan/environment/base.env#L5
This complicates the situation now, doesn't it because we have essentially have two site users

**Comment by roll** [comment]
Oops sorry, I didn't know it was meaningful. I renamed stuff to ridl when we were migrating to make naming more useful within UNHCR projects
