### ISSUE TITLE
Enable ckanext-collaborators (Dataset level permissions)

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-unhcr#276]
Install [ckanext-collaborators](https://github.com/okfn/ckanext-collaborators) and enable it so we can test it works as expected. It just requires creating some tables on startup.

This extension allows Data Container admins to add "Collaborators" to datasets. These can have two roles:
* Members (can download private datasets)
* Editors (can edit datasets)

The UI is in the dataset page > Manage > Collaborators

I think all should work as expected as we have used it in another project with similar authorization requirements but worth playing around.

**Comment by chris48s** [comment]
I had a quick go at installing this, but I fell at the first hurdle with `Exception: The auth function 'package_update' is already implemented in 'unhcr'`. I guess there is a conflict because both `ckanext-collaborators` and `ckanext-unhcr` are trying to implement the `package_update` auth hook, but I have no idea how to go about resolving that. Any guidance on how to tackle it?

**Comment by amercader** [comment]
This is caused by a bug in CKAN core that prevents core actions from being extended with the `chained_action` decorator (https://github.com/ckan/ckan/pull/4509). This was backported to CKAN 2.8.4 so hopefully upgrading the upstream images should fix the issue:

https://github.com/okfn/docker-ckan-unhcr#updating-upstream-ckan-images

You can check what version your site is using the `status_show` action: https://ridl-uat.unhcr.org/api/action/status_show
