### ISSUE TITLE
New admin activity stream, showing curation activities and downloads

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-unhcr#284]
Datasets currently have a separated tab called "Curation activity" that displays activities related to the curation process. This is only shown to users who can edit the dataset. (ie org editors and admins).

![Screenshot_2020-04-23 MDM Metadata - RIDL](https://user-images.githubusercontent.com/200230/80084810-a976b700-8557-11ea-9f70-e30c5393d065.png)
![Screenshot_2020-04-23 Urban Profiling Thessaloniki Greece - RIDL](https://user-images.githubusercontent.com/200230/80084818-ada2d480-8557-11ea-937f-66533b7058c6.png)

The goal is to add new internal only activities like downloads into this tab to avoid adding more. We can rename it to "Internal activities" for now.

* The tab is added in the [`read_base.html`](https://github.com/okfn/ckanext-unhcr/blob/fdebd7d2dfeed6836daa20fe4716c7ca466f6292/ckanext/unhcr/templates/package/read_base.html#L17) template
* The link calls a custom action in the [`deposited_dataset.py`](https://github.com/okfn/ckanext-unhcr/blob/fdebd7d2dfeed6836daa20fe4716c7ca466f6292/ckanext/unhcr/controllers/deposited_dataset.py#L337) controller. We should probably move it to the `extended_package.py` one as activities won't be curation specific from now on.
* This calls our custom `package_activity_list_html` action with the `get_curation_activities` param in the context set to True. All `*_activity_*` actions accept this parameter to return either the normal activities or the internal ones. We'll need to update them all to also include download ones.
* TODO code will be slightly different depending on who can see download activities:

  - If editors can (same as current curation activities) we just rename the param and include the download activities to the current curation ones.
 - If only admins can see downloads then we will need to filter the internal activities returned depending on whether the user is an admin or not of the data container (curation only if it's an editor, curation+ download if it's an admin). I'd probably determine this at the controller level and pass  `get_curation_activities` and / or `get_admin_activities` depending on the user role, and then the actions would act accordingly.
* In any case we will need to add a custom render function for the `resource download` activity. This is done via a lovely monkey-patch in [here](https://github.com/okfn/ckanext-unhcr/blob/fdebd7d2dfeed6836daa20fe4716c7ca466f6292/ckanext/unhcr/plugin.py#L46)

**Comment by chris48s** [comment]
When I did https://github.com/okfn/ckanext-unhcr/pull/280 I set it up so that when a user downloads a resource, we log a resource_download action with

```
user_id: user_id
object_id: resource_id
```

..which makes sense conceptually because the thing that we're actually downloading is a resource: user downloads resource.

Now that I'm working on this issue, what I'm realising is that there are no actions in the CKAN core API for querying activities where the `object_id` is a resource so its a bit hard to work with.

One option is to query the DB directly with SQLAlchemy when we need these activities (like we did on the metrics dashboard), but I'm wondering (while we're still at a stage where this feature is deployed in UAT but not production yet, so its quite easy to change it) if it would have made more sense to log the activity so that the `object_id` is the parent `package_id` (not the individual `resource_id`) and save the resource dict in the `data` key. I think then we could take advantage of the package_activity actions in the core API to query it and maybe simplify things a bit in the UNHCR codebase..

**Comment by amercader** [comment]
@chris48s I think it makes more sense to store the download activities against the datasets and use `package_activity_list`. We are already overriding it to handle the curation activities and as you say we can store the actual resource id in the `data` object.

**Comment by chris48s** [comment]
Still waiting on concrete feedback, but I think the direction we're heading on this is that resource download activities can be viewed by container admins.

**Comment by chris48s** [comment]
WIP on this at https://github.com/okfn/ckanext-unhcr/tree/284-internal-activity but still more to do..
