### ISSUE TITLE
Upgrade to CKAN 2.8.5

### ISSUE THREAD

**Issue by chris48s** [okfn/ckanext-unhcr#401]
Although we're not ready to embark on the 2.9 upgrade yet, there are no blockers to upgrading to this patch release

**Comment by amercader** [comment]
@chris48s I've updated the upstream `openknowledge/ckan-base:2.8` and `openknowledge/ckan-dev:2.8` images. For your local install you'll need to [follow the isntructions](https://github.com/okfn/docker-ckan-unhcr-aws#updating-upstream-ckan-images). I had a play around and everything seemed to work fine, and actually the Travis tests have been running on 2.8.5 since it was released.

I'm not sure if ECS will pull the upstream images on every build or there is some kind of cache in place. I guess we will find out in the next deploy.

**Comment by chris48s** [comment]
We're now on CKAN 2.8.6 in production
