### ISSUE TITLE
Create CKAN resources from Kobo Toolbox data

### ISSUE THREAD

**Issue by chris48s** [okfn/ckanext-unhcr#626]
If a dataset has a `kobo_asset_id` set (see #625 ) and the user has a kobo API token set on their profile (see #624 ), we want to give the user the ability to create a CKAN resource by extracting data directly from Kobo instead of uploading a file.

There are two possible ways we can extract data from Kobo using an asset id.

---

## /data

One option to use the `/data` endpoint. For example:

```
curl "https://kobo.unhcr.org/api/v2/assets/aRB6Wetaj9cSxDFTzT3tJj/data/" -H "Authorization: token <YOUR-TOKEN>" -H "Accept: application/json"
```

This gives us a "live" export of the data.
Docs: https://kobo.unhcr.org/api/v2/assets/aRB6Wetaj9cSxDFTzT3tJj/data/

**Tradeoffs:**

- The `/data` endpoint is paginated with `?limit=&offset=` params. This forum thread suggests the max value for `limit` is 30,000 https://community.kobotoolbox.org/t/does-kobotoolbox-support-paginated-api/11260/2 so for a large dataset we might have to page over multiple requests to fetch all the data and then stitch them together into a single file
- The `/data` endpoint supports 3 formats:
    - `?format=xml`
    - `?format=geojson`
    - `?format=json`
  The most useful format for users is going to be CSV though, so we will be responsible for turning the array of JSON objects into a CSV ourself (although the conversion should be pretty trivial)
- The `/data` endpoint will always pull the latest survey data. The user doesn't need to export anything or interact with Kobo in order to pull new data into RIDL
- The `/data` endpoint supports filtering data by a query param: `?query={"field":"value"}`. More docs on the query syntax at https://docs.mongodb.com/manual/reference/operator/query/

## /exports

The other option is to use the `/exports` endpoint. For example

```
curl "https://kobo.unhcr.org/api/v2/assets/aRB6Wetaj9cSxDFTzT3tJj/exports/" -H "Authorization: token <YOUR-TOKEN>" -H "Accept: application/json"
```

This gives us a list of any exports the user has created.

**Tradeoffs:**

- The `/exports` endpoint is easy to work with. It just gives us a list of files we can download.
- The `/exports` endpoint only lists exports the user has created. If the user wants to import 'new' data, they have to create an export in Kobo first.
- Kobo has quite a lot of options for the user when they create an export:
  ![Screenshot at 2021-07-09 14-02-05](https://user-images.githubusercontent.com/6025893/125099345-d4ebb000-e0cf-11eb-9017-81d2e57d3187.png)
  It would be hard to fully reproduce all of those options from the data endpoint.

---

The current thinking from the client is that we will **definitely** need the ability to create a new resource from Kobo based on querying the `/data` endpoint. We **might** also want the ability to create resources from existing exports (TBC).

If a dataset has a `kobo_asset_id` set and the user has a Kobo API token set on their profile, we're going to need to offer the user the ability to create a new "Data file" resource based on querying the `/data` endpoint. We will also need some sort of form to select a query or filter, although we should try to pin down a subset of filters or functionality we need to implement. Lets not build a complete builder for MongoDB's query syntax. Would it make most sense to implement the filter/query form as a seperate page or show it inline on the "new resource" form using a scheming snippet?

Instead of uploading a resource we will pull the resource from the Kobo API. The user will still need to fill in the resource metadata fields themselves.

If we also need the ability to create a RIDL resource from a Kobo export, we could replace the "Upload" UI element on the "new resource" form with a drop-down list of exported files that the user can choose from.

The other part of this jigsaw is we will need a way to either create a CSV based on the Kobo /data API or download an existing export via the Kobo API and then present it to `resource_create` as an "upload". What is the best way to do this?

---

**Questions:**
- Would it make most sense to implement the filter/query form as a seperate page or show it inline on the "new resource" form using a scheming snippet?
- What is the best way to present a file we have constructed from Kobo's API to `resource_create` as an "upload"?
- What are the requirements around using being able to filter the data as part of the import process?
- Do users want to be able to import exports they've created from Kobo into RIDL or is the raw data import and some filters all we need?

**Comment by amercader** [comment]
Latest update after discussion with the client:

* Kobo datasets created as part of the workflow described in https://github.com/okfn/ckanext-unhcr/issues/625#issuecomment-889132441 should have one resource automatically created: the questionnaire used in XLSX format (eg https://kobo.unhcr.org/api/v2/assets/aRB6Wetaj9cSxDFTzT3tJj.xls). The questionnaire should be downloaded and stored as a RIDL file
* If possible, another resource should be created with the questionnaire as a PDF (to be confirmed if this is possible)
* On the resource form, Kobo datasets will have a "Kobo Data" button instead of the "Upload" one. This should be the case both when creating and updating the resource (We will need to override the `image-upload` js module)
* For the first iteration we will just store the Kobo data as a JSON file. In a next phase we might need to translate to CSV
* It probably makes sense to implement the fetching of data from Kobo and uploading it to RIDL as a background job. So we would create an empty resource (perhaps with a placeholder name that says "Data being imported from Kobo...") and once the process is completed we update/patch the resource uploading the generated file.
* Let's not complicate the interface for getting the data initially and don't implement any support for filtering.
