### ISSUE TITLE
Datastore error UAT

### ISSUE THREAD

**Issue by avdata99** [okfn/ckanext-unhcr#716]
Possible error while datastore try to read the

`Could not load view: DataProxy returned an error (Data transformation failed. HTTPError: HTTP Error 500: Internal Server Error)`

![image](https://user-images.githubusercontent.com/3237309/136373796-2c80cadd-cb88-4116-801f-9152fb9c6c47.png)

### Logs

The error should be 403
Why datastore don't use a valid user to download datasets?

<pre>
| 1633605292837  2021-10-07 11:14:52,836 INFO [ckan.config.middleware.flask_app] 200 /dataset/my-third-survey/resource/90b5cce4-f25f-4fb3-8767-ca36b883cffc/view/31826b75-9076-4757-84fc-cf10024d9ccb render time 0.510 seconds 
| 1633605295048  2021-10-07 11:14:55,048 ERROR [ckan.config.middleware.flask_app] 'Saml2AuthPlugin' object has no attribute 'abort' 
| 1633605295048  Traceback (most recent call last): 
| 1633605295048  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request 
| 1633605295048  rv = self.dispatch_request() 
| 1633605295048  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request 
| 1633605295048  return self.view_functions[rule.endpoint](**req.view_args) 
| 1633605295048  File "/srv/app/src/ckanext-unhcr/ckanext/unhcr/utils.py", line 83, in view_wrapper 
| 1633605295048  return toolkit.abort(403, "Forbidden") 
| 1633605295048  File "/srv/app/src/ckan/ckan/lib/base.py", line 59, in abort 
| 1633605295048  result = item.abort(status_code, detail, headers, comment) 
| 1633605295048  AttributeError: 'Saml2AuthPlugin' object has no attribute 'abort' 

| 1633605295066  2021-10-07 11:14:55,066 
  INFO [ckan.config.middleware.flask_app] 
  <b>500</b>
  /dataset/8aa31808-4096-405a-a071-a846d3ff7414/resource/90b5cce4-f25f-4fb3-8767-ca36b883cffc/download/aeuzyqjesykau2hfs5zwvq_data.xls
  render time 0.036 seconds 
</pre>

Questionnaire (XLS) works

![image](https://user-images.githubusercontent.com/3237309/136373618-d7413c5d-2217-491a-86ff-2fe7ac47699b.png)

CSV resource works
![image](https://user-images.githubusercontent.com/3237309/136373644-e065c39a-d414-473d-9e03-1b0061964756.png)

Only XLS resource fails

**Comment by amercader** [comment]
DataProxy is an old external service that the Recline view falls back to when the data is not in the DataStore. DataProxy does not use any form of authentication, so it should not be able to access any RIDL files at all.
The issue here is that the data didn't get into the DataStore for some reason (most likely because the XLS files have "invalid" formatting like combined cells, empty rows, etc).
Standard CKAN instances have a green "Data API" button if the data was uploaded to the DataStore (by DataPusher or Xloader) but in RIDL you need to check if the resource API metadata has `datastore_active: True` or just call `datastore_search` directly, eg for [this](https://ridl-uat.unhcr.org/dataset/my-third-survey/resource/01274eee-1831-4aa1-871b-734514ca81e0) resource: https://ridl-uat.unhcr.org/api/action/datastore_search?id=01274eee-1831-4aa1-871b-734514ca81e0

The error should appear in Manage > DataStore but if there was an exception in DataPusher the job might be stuck in pending and you will need to check the datapusher container logs.

I'd check the logs to see if it's something easy to fix but if not, all this situation should improve as part of the DataStore backend changes in Phase 6 (xloader, datatables view, etc) so I'd suggest park it for now.

**Comment by avdata99** [comment]
Fixed with #701
