### ISSUE TITLE
User register form improvement

### ISSUE THREAD

**Issue by avdata99** [okfn/ckanext-unhcr#866]
Partner account request page displays an error
message that indicates if a user account has already been registered. Someone can
use this information to enumerate valid usernames in preparation for password
guessing attacks.

Remediation
 - To send same response for both valid and invalid input within the given field.
   - Another way is to always say something like *Thanks for attempt to register, you'll receive an email if the account is approved* 
 - To implement a CAPTCHA on the affected form.
   - AWS include a captcha service using [AWS WAF ](https://docs.aws.amazon.com/waf/latest/developerguide/waf-captcha-how-it-works.html)
   - CKAN is ready to implement Google Recaptcha for the `/user/register` URL
 - To enforce accounts security we can implement 2FA.

![image](https://user-images.githubusercontent.com/3237309/187694792-eb66dee2-64cd-4960-91aa-4685e3500398.png)

**Comment by amercader** [comment]
There is no easy solution for this.
> To send same response for both valid and invalid input within the given field. 

Legit users need to know if their new user request has been approved or not. If they don't receive a notification they won't know if it's because the user name already existed or because it was rejected (we can't tell them in the email that it was because of the user name because that has the same effect as the error message)
Anything that involves telling the user that the user name exists brings us back to the original problem. The only option is to make *harder* for attackers to keep guessing user names, for instance making them wait an increasing amount of time to register another account if there is an existing user name error.

> To implement a CAPTCHA on the affected form. 

We alredy use reCaptcha on this form right?

![Screenshot 2022-09-01 at 10-38-19 Register - RIDL](https://user-images.githubusercontent.com/200230/187870925-1f173494-f4f8-43bb-b853-7129dab7e8e4.png)

> To enforce accounts security we can implement 2FA

This is definitely possible, but it would involve a significant effort. We need to assess the thread model, in this case an attacker could potentially access a partner account, which is highly limited in what they can perform on the site.
